### ISSUE TITLE
sideloading of entities

### ISSUE THREAD

**Issue by niv** [ruby-grape/grape-entity#17] opened 2013-07-18 19:23 UTC
I'm trying to sideload entities with specified roots.

For example:
```
class A::Entity < Entity
  root 'aa', a'
end
class B::Entity < Entity
  root 'bb', 'b'
end
...
get do
  present A.all
  present B.all
end
```

Should result in this hash:
```{aa => [...], bb => [...]}```

However, present overwrites the last results, so only 'bb' remains.

I can "fix" this by merging @body in Endpoint#present, like so:

```
representation = @body.merge(representation) if @body
body representation
```

However, that will probably break horribly if there are no roots defined. Is there a better way to do this?

Ideally, i'd want the option to specify sideloadable relations in Grape::Entity itself and they would get pulled in automatically when calling 'present' with a Entity.

**Comment by Fryie** [comment] 2015-07-23 09:31
I think sideloading is a very important feature for writing maintainable and scalable APIs. However, it seems that this feature request implies making or reconsidering a number of design choices.

There's a couple of ways I could imagine this to work:
- create a method that takes a block and collects all representations in the block similar to the monkeypatch mentioned above, but that would just raise a meaningful error if any of the representations has no root element (sideloading does not make sense without root elements)
- create a new method that takes an array of entities like so: ```present_all [{ entity: users, with: Entity::User, root: 'users'}, { entity: articles, with: Entity::Article, root: 'articles' }]```. It would require the ```root``` option to be passed in and ignore the root property from the Entity. This has the flaw that information about the root element has to be repeated in several places, and that the option specified in the entity is ignored. Alternatively, similar to the first method, it could just rely on the root option of the entity itself and raise a meaningful error if that doesn't exist (or if two entity roots have the same name)

Any thoughts?

**Comment by marshall-lee** [comment] 2015-08-10 22:08
It seems that it's a wrong repo for asking this feature. `present` macro is a Grape's thing, not Grape::Entity's.

I also don't like this feature as it described. It's just obscure because it requires merging. Merge hashes? How — deep or not deep? What if one  thing is a hash but other thing is an array?

Can this idea be improved? Maybe, I don't know.

But something very similar is already implemented in Grape::Entity: you can combine two or more entities in one with `:using` option. I just can't understand why do you need anything else?

**Comment by marshall-lee** [comment] 2015-08-10 22:08
Am I missing something?

**Comment by Fryie** [comment] 2015-08-10 22:17
Sideloading is not about merging or embedding records. It's about having:
`{
   articles: [...],
   comments: [...]
}`

That is loading related records as part as the same request.
Embedding is another issue altogether, it generally implies or works best with hierarchical relationships.

See e.g. [here](https://developer.zendesk.com/rest_api/docs/core/side_loading). Something similar happens [here](http://jsonapi.org/format/#document-compound-documents).

**Comment by Fryie** [comment] 2015-08-10 22:19
Also if you work with something like EmberJS, that's how Ember expects related records to be included.

**Comment by marshall-lee** [comment] 2015-08-11 08:22
Ah, sorry, I just haven't known that this thing is called sideloading :)

Well, then I can say that the way it proposed in the first post is wrong. There are `A.all` and `B.all` that are not about what you describe.

Sideloading is about *associations* but Grape::Entity is more abstract and doesn't know anything about them. ActiveModel::Serializer knows about associations because it knows about *models* but Grape::Entity operates with any kind of object.

So this thing *can be* implemented upon existing Grape::Entity features — you just should give it a properly constructed object that have `articles` and `comments` properties. It's more DIY than in ActiveModel::Serializer but I don't see how automatic pulling of associations could be a scope of Grape::Entity.

**Comment by dblock** [comment] 2015-08-11 12:38
Maybe we (someone :)) can begin by writing a Grape extension that replaces `present` and that behaves in a different way? At the very least we'll see what that looks like in code.

**Comment by marshall-lee** [comment] 2015-08-11 14:11
Trying to explain my thoughts with some PoC in pseudo-ruby:

```ruby

# models

class User
end

class Post
  belongs_to :user
  has_many :comments
end

class Comment
  belongs_to :user
end

# decorator for presentation logic

class SideloadablePost
  def initialize(post)
    @post = post
  end
  
  def post
    @post
  end

  def comments
    post.comments
  end

  def users
    [post.user] + comments.map(&:user)
  end
end

# entities

class PostEntity < Grape::Entity
  expose :id
  expose :title
  expose :body
  expose :user_id
  expose :comment_ids
end

class CommentEntity < Grape::Entity
  expose :id
  expose :body
  expose :user_id
end

class UserEntity < Grape::Entity
  expose :id
  expose :name
end

class SideloadablePostEntity < Grape::Entity
  expose :post, using: 'PostEntity'
  expose :comments, using: 'CommentEntity'
  expose :users, using: 'UserEntity'
end

# some api

post = Post.find(params[:id])
sideloadable_post = SideloadablePost.new(post)
present sideloadable_post, with: SideloadablePostEntity
```

So the problem is only about having a convenient tool for constructing decorators like `SideloadablePost`. And I don't think that it's a Grape::Entity's responsibility.

**Comment by marshall-lee** [comment] 2015-08-11 14:20
Implementing a generic `Sideloadable` requires taking a concept of association (`belongs_to`, `has_many`). But Grape::Entity doesn't know about them and I don't think it should.

**Comment by dblock** [comment] 2015-08-13 13:26
Lets agree that grape-entity automatically pulling associations is definitely beyond the scope of this library. I do think the instances being presented can be pulling whatever they need and expose the result.

I believe we're able to do what @niv is asking by creating a Grape::Entity that models the combined entity with both a's and b's as in the example on the very top. However generically I can see how one wants an API that just has a ton of stuff in it from all over the place. In fact, a typical hypermedia API like HAL exposes mixed type data in its embedded output. Some excellent libraries like Roar do this very well, eg.

```ruby
module SplinesPresenter
  include Roar::JSON::HAL
  include Roar::Hypermedia
  include Grape::Roar::Representer

  collection :splines, extend: SplinePresenter, embedded: true
  collection :foobars, extend: FoobarPresenter, embedded: true
end
```

That `embedded: true` above causes the collection to be merged as `splines: [ ... ]` and `foobars: [ ...]` onto 'embedded: { ... }` in the top level of the JSON, as per HAL or JSONAPI spec. This kind of stuff is why I prefer to use Roar/HAL to grape-entity, it's less freedom and more discipline.

The `SideloadablePostEntity` above accomplishes something very similar. Does this answer the original question, @niv? I think we should close this without any action items.

**Comment by niv** [comment] 2015-08-13 17:24
Oh, wow, lots of activity here. Yeah, that seems a reasonable way to go about it and I have no objections to shelving this.

**Comment by dblock** [comment] 2015-08-13 17:42
The author of the issue has spoken. Thanks all! Add more comments here will be happy to read and continue a discussion.

**Closed by dblock** 2015-08-13 17:42 UTC
Labels: feature
